new tile in quickstarts
Teradata/developer-resources pull request #162
Opened 2024-11-29 19:08 UTC by ObedVega

## Description

### What's included?

- One
- Two
- Three
#### General Tests for Every PR

Please make sure your PR adheres to the following requirements:

- [ ] `npm run start` still works.
- [ ] `npm run build` still works.
- [ ] Code adheres to project style guidelines (e.g., linting, formatting).
- [ ] Any new dependencies have been added to the appropriate files.
- [ ] The changes do not introduce new issues or regressions.

### Screenshots or Visual Updates (if applicable)

2024-12-03 21:22 UTC, bsahitya commented
Looks good @ObedVega. Can we request for translations in other languages too?
Translation keys are being displayed in other languages due to missing translations.

2024-12-03 21:57 UTC, bsahitya reviewed
Looks good @ObedVega. Can we request for translations in other languages too?
Translation keys are being displayed in other languages due to missing translations.

2025-01-14 16:48 UTC, owilliams320 requested changes
@ObedVega can we fill in the the other languages with english for now so the keys dont show up? See this link https://developers.teradata.com/pr-preview/pr-162/es/quickstarts/

2025-01-21 19:59 UTC, owilliams320 approved these changes

2025-01-21 20:00 UTC, merged